use config file instead of console menu
emoisback/Helldivers-2-Internal-Hack-Dll-Proxy-PoC pull request #40
Opened 2024-03-07 19:17 UTC by Kahdeg-15520487

2024-03-07 19:36 UTC, rogeriocamorim commented
What is the advantage of that? The console looks more user-friendly.
Also with the console maybe in the future we can have enable/disable on the go.

2024-03-07 19:45 UTC, rogeriocamorim commented
Gotcha was not updated on the recent facts.

2024-03-07 19:48 UTC, Kahdeg-15520487 commented
> but console is what make we got detected easly,
i removed all the console stuff

> is this has been tested and work properly?..
i have tested it locally, would need to test more in depth later.
the custom value stuff work too.

> im at bed rn gonna look into it tmrw.
and it way past my bedtime here too.
i just throw it out asap so that other can also chime in

2024-03-07 19:48 UTC, gir489returns commented
This doesn't address the root detection in that Game Guard is looking for the word hack.

2024-03-07 19:52 UTC, Kahdeg-15520487 commented
if it is just string stuff then i just replace the wording

2024-03-07 19:59 UTC, rogeriocamorim commented
I would rename all SpeedHack (even variables) to SpeedModifier just in case.

2024-03-07 20:03 UTC, zDestinate commented
I have one without the console. It still got detected.

2024-03-07 20:14 UTC, rogeriocamorim commented
I got this code and still detect it.

2024-03-07 20:22 UTC, Kahdeg-15520487 commented
> I got this code and still detect it.

just finished a run with this code compiled, not detected

2024-03-07 20:25 UTC, noobLue commented
> I got this code and still detect it.

compile in release mode not debug

2024-03-07 20:30 UTC, rogeriocamorim commented
> > I got this code and still detect it.
> 
> compile in release mode not debug

q: Why debug mode detects?

2024-03-07 20:38 UTC, DeathWrench commented
Made a PR for this PR that fixes some stuff
https://github.com/Kahdeg-15520487/hd2/pulls

2024-03-07 20:46 UTC, noobLue commented
> > > I got this code and still detect it.
> > 
> > 
> > compile in release mode not debug
> 
> q: Why debug mode detects?

Debug mode includes bunch of extra information in the dll that release mode doesn't.

2024-03-07 20:58 UTC, gir489returns commented
I'm getting code 1013 now no matter what I do. Fuck these fucking gooks.

2024-03-07 22:45 UTC, gir489returns requested changes
Garbage. I suggest @emoisback do his own, but if he wants this, it needs improvement.

2024-03-07 22:45 UTC, gir489returns commented on version/dllmain.cpp
> +	ini["features"]["ohk"] = gData.OHK ? "1" : "0";
All of these strings can be potentially looked for by GameGuard. XORing them does nothing, as that only affects the at-rest binary. Once the game loads this into memory, these strings will be in plain text. We should hash these instead.

2024-03-07 22:45 UTC, gir489returns commented on version/dllmain.cpp
> +		gData.OHK = ini["features"]["ohk"] == "1";
This is beyond retarded. Either the INI class should return datatypes that we can template, or the INI class returns an object that we just cast to gData. FOH with that fucking C-style bullshit.

2024-03-07 22:45 UTC, gir489returns commented on version/dllmain.cpp
> +	// Initialize the proxy for the DLL
Massive whitespace change for no reason.

2024-03-07 22:45 UTC, gir489returns commented on version/dllmain.cpp
> +	switch (ul_reason_for_call)
Massive whitespace change for no reason.

2024-03-07 23:32 UTC, emoisback commented
ok thanks ill rewrite this to use

something like this

 bool boolValue = config.GetValue<bool>("HashInfHealthWithKey");

2024-03-08 00:37 UTC, UnholyScribe commented
so are we getting a update?? lol

2024-03-08 00:48 UTC, KingofEverythingg commented
Yall have a discord?

2024-03-08 01:13 UTC, Kahdeg-15520487 commented
tks for code review, i will restart work for this again.

2024-03-08 01:13 UTC, closed without merging